version 1.0

## ─────────────────────────────────────────────────────────────────────────────
## rename_bam_chroms.wdl
##
## Workflow
## ────────
## Rename BAM/CRAM chromosome names from Ensembl style (1, 2, KI270419.1 …)
## to UCSC hg38 style (chr1, chr2, chrUn_KI270419v1 …) using the
## official UCSC chromAlias table and samtools reheader.
##
## The reference FASTA (+ .fai index) is required because the input is a
## CRAM — samtools must decode the CRAM reads before writing BAM output.
##
## Steps inside the task
## ─────────────────────
##   1. rename_bam_chroms.py  – rewrites @SQ header lines → tmp BAM
##      (uses -T ref.fasta so samtools reheader can decode the CRAM)
##   2. samtools sort          – coordinate-sort → final BAM
##   3. samtools index         – produce the .bai index
##
## Inputs
## ──────
##   input_bam         File    – input BAM/CRAM with Ensembl-style contig names
##   input_bai         File?   – optional pre-existing index
##   ref_fasta         File    – reference FASTA (required for CRAM decoding)
##   ref_fasta_fai     File    – .fai index of the reference FASTA
##   rename_script     File    – rename_bam_chroms.py
##   chrom_alias       File?   – chromAlias.txt(.gz); downloaded if omitted
##   unmapped          String  – "keep" (default) or "drop"
##   sample_id         String  – prefix for output filenames
##
## Outputs
## ───────
##   renamed_bam       File    – output BAM with UCSC-style contig names
##   renamed_bai       File    – BAI index of the output BAM
## ─────────────────────────────────────────────────────────────────────────────

workflow RenameBamChroms {

    input {
        File    input_bam
        File?   input_bai
        File    ref_fasta
        File    ref_fasta_fai
        File    rename_script
        File?   chrom_alias
        String  unmapped    = "keep"
        String  sample_id

        # Runtime overrides
        String  docker      = "us.gcr.io/broad-gatk/gatk:4.5.0.0"
        Int     cpu         = 4
        Int     mem_gb      = 16
        Int     disk_gb     = 200
        Int     preemptible = 2
    }

    call RenameContigs {
        input:
            input_bam     = input_bam,
            input_bai     = input_bai,
            ref_fasta     = ref_fasta,
            ref_fasta_fai = ref_fasta_fai,
            rename_script = rename_script,
            chrom_alias   = chrom_alias,
            unmapped      = unmapped,
            sample_id     = sample_id,
            docker        = docker,
            cpu           = cpu,
            mem_gb        = mem_gb,
            disk_gb       = disk_gb,
            preemptible   = preemptible
    }

    output {
        File renamed_bam = RenameContigs.renamed_bam
        File renamed_bai = RenameContigs.renamed_bai
    }

    meta {
        author:      "Generated by Claude"
        description: "Rename BAM/CRAM contigs from Ensembl to UCSC hg38, sort, and index."
    }
}


# ─────────────────────────────────────────────────────────────────────────────
# Task: RenameContigs
# ─────────────────────────────────────────────────────────────────────────────
task RenameContigs {

    input {
        File    input_bam
        File?   input_bai
        File    ref_fasta
        File    ref_fasta_fai
        File    rename_script
        File?   chrom_alias
        String  unmapped    = "keep"
        String  sample_id

        String  docker      = "us.gcr.io/broad-gatk/gatk:4.5.0.0"
        Int     cpu         = 4
        Int     mem_gb      = 16
        Int     disk_gb     = 200
        Int     preemptible = 2
    }

    String output_bam = "~{sample_id}.ucsc.bam"
    String output_bai = "~{sample_id}.ucsc.bam.bai"

    String alias_arg = if defined(chrom_alias)
                       then "--alias ~{chrom_alias}"
                       else ""

    command <<<
        set -euo pipefail

        echo "[$(date '+%H:%M:%S')] Starting contig rename for ~{sample_id}"
        samtools --version | head -1
        python3 --version

        # ── Step 1: rewrite header → tmp BAM ──────────────────────────────
        # Pass the reference FASTA so samtools reheader can decode the CRAM.
        TMP_BAM="~{sample_id}.tmp.bam"

        python3 ~{rename_script} \
            --bam      ~{input_bam} \
            --out      "${TMP_BAM}" \
            --ref      ~{ref_fasta} \
            ~{alias_arg} \
            --unmapped ~{unmapped}

        echo "[$(date '+%H:%M:%S')] Header rename complete. Sorting..."

        # ── Step 2: coordinate-sort ────────────────────────────────────────
        samtools sort \
            -@ ~{cpu} \
            -T "sort_tmp" \
            -o ~{output_bam} \
            "${TMP_BAM}"

        rm -f "${TMP_BAM}"
        echo "[$(date '+%H:%M:%S')] Sort complete. Indexing..."

        # ── Step 3: index → .bai ──────────────────────────────────────────
        samtools index -@ ~{cpu} ~{output_bam}


    >>>

    output {
        File renamed_bam = output_bam
        File renamed_bai = output_bai
    }

    runtime {
        docker:      docker
        cpu:         cpu
        memory:      "~{mem_gb} GB"
        disks:       "local-disk ~{disk_gb} HDD"
        preemptible: preemptible
        maxRetries:  1
    }

    meta {
        description: "Rename BAM/CRAM contig names, sort, and index. Requires reference FASTA for CRAM decoding."
    }

    parameter_meta {
        input_bam:     {help: "Input BAM or CRAM with Ensembl-style contig names"}
        input_bai:     {help: "Optional BAI/CRAI index for localisation"}
        ref_fasta:     {help: "Reference FASTA — required for CRAM decoding (e.g. Homo_sapiens_assembly38.fasta)"}
        ref_fasta_fai: {help: ".fai index of the reference FASTA"}
        rename_script: {help: "rename_bam_chroms.py script"}
        chrom_alias:   {help: "UCSC chromAlias.txt(.gz) — downloaded from UCSC at runtime if omitted"}
        unmapped:      {help: "'keep' to leave unrecognised contigs unchanged; 'drop' to remove their @SQ lines"}
        sample_id:     {help: "Prefix for output files: <sample_id>.ucsc.bam and .bai"}
    }
}
