version 1.0

## ─────────────────────────────────────────────────────────────────────────────
## rename_bam_chroms.wdl
##
## Workflow
## ────────
## Rename BAM chromosome names from Ensembl style (1, 2, KI270419.1 …)
## to UCSC hg38 style (chr1, chr2, chrUn_KI270419v1 …) using the
## official UCSC chromAlias table and samtools reheader.
##
## Inputs
## ──────
##   input_bam         File    – input BAM with Ensembl-style contig names
##   input_bai         File?   – optional pre-existing index (used for localisation)
##   rename_script     File    – rename_bam_chroms.py
##   chrom_alias       File?   – chromAlias.txt or chromAlias.txt.gz
##                               (downloaded from UCSC at runtime if not provided)
##   unmapped          String  – "keep" (default) or "drop" for contigs absent
##                               from the alias table
##   sample_id         String  – used to name the output BAM
##
## Outputs
## ───────
##   renamed_bam       File    – output BAM with UCSC-style contig names
##   renamed_bai       File    – BAI index of the output BAM
##
## Runtime
## ───────
## Designed for Google Cloud / Terra (Cromwell).
## Adjust docker / memory / disk_gb as needed.
## ─────────────────────────────────────────────────────────────────────────────

workflow RenameBamChroms {

    input {
        File    input_bam
        File?   input_bai
        File    rename_script
        File?   chrom_alias          # optional: supply local copy to skip download
        String  unmapped  = "keep"   # "keep" | "drop"
        String  sample_id

        # Runtime overrides
        String  docker    = "us.gcr.io/broad-gatk/gatk:4.5.0.0"  # has samtools + python3
        Int     cpu       = 2
        Int     mem_gb    = 8
        Int     disk_gb   = 100
        Int     preemptible = 2
    }

    call RenameContigs {
        input:
            input_bam     = input_bam,
            input_bai     = input_bai,
            rename_script = rename_script,
            chrom_alias   = chrom_alias,
            unmapped      = unmapped,
            sample_id     = sample_id,
            docker        = docker,
            cpu           = cpu,
            mem_gb        = mem_gb,
            disk_gb       = disk_gb,
            preemptible   = preemptible
    }

    output {
        File renamed_bam = RenameContigs.renamed_bam
        File renamed_bai = RenameContigs.renamed_bai
    }

    meta {
        author:      "Generated by Claude"
        description: "Rename BAM contigs from Ensembl to UCSC hg38 naming using samtools reheader."
    }
}


# ─────────────────────────────────────────────────────────────────────────────
# Task: RenameContigs
# ─────────────────────────────────────────────────────────────────────────────
task RenameContigs {

    input {
        File    input_bam
        File?   input_bai
        File    rename_script
        File?   chrom_alias
        String  unmapped    = "keep"
        String  sample_id

        String  docker      = "us.gcr.io/broad-gatk/gatk:4.5.0.0"
        Int     cpu         = 2
        Int     mem_gb      = 8
        Int     disk_gb     = 100
        Int     preemptible = 2
    }

    String output_bam = "~{sample_id}.ucsc.bam"
    String output_bai = "~{sample_id}.ucsc.bam.bai"

    # Build the --alias argument conditionally:
    # if chrom_alias is supplied, pass it; otherwise omit and let the
    # script download from UCSC at runtime.
    String alias_arg = if defined(chrom_alias)
                       then "--alias ~{chrom_alias}"
                       else ""

    command <<<
        set -euo pipefail

        echo "[$(date '+%H:%M:%S')] Starting contig rename for ~{sample_id}"

        # Verify samtools is available
        samtools --version | head -1

        # Verify Python3 is available
        python3 --version

        # Run the rename script
        python3 ~{rename_script} \
            --bam      ~{input_bam} \
            --out      ~{output_bam} \
            ~{alias_arg} \
            --unmapped ~{unmapped}

        echo "[$(date '+%H:%M:%S')] Done. Verifying output..."

        # Sanity check: confirm chr-prefixed contigs appear in new header
        samtools view -H ~{output_bam} | grep "^@SQ" | head -5

        # Report contig count
        N=$(samtools view -H ~{output_bam} | grep -c "^@SQ" || true)
        echo "  Output BAM has ${N} @SQ (contig) header lines."

        echo "[$(date '+%H:%M:%S')] Finished ~{output_bam}"
    >>>

    output {
        File renamed_bam = output_bam
        File renamed_bai = output_bai
    }

    runtime {
        docker:      docker
        cpu:         cpu
        memory:      "~{mem_gb} GB"
        disks:       "local-disk ~{disk_gb} HDD"
        preemptible: preemptible
        maxRetries:  1
    }

    meta {
        description: "Rename BAM contig names from Ensembl to UCSC using rename_bam_chroms.py and samtools reheader."
    }

    parameter_meta {
        input_bam:     {help: "Input BAM with Ensembl-style contig names (e.g. 1, 2, KI270419.1)"}
        input_bai:     {help: "Optional BAI index; supplying it ensures localisation alongside the BAM"}
        rename_script: {help: "rename_bam_chroms.py script"}
        chrom_alias:   {help: "UCSC chromAlias.txt(.gz) — downloaded from UCSC if omitted"}
        unmapped:      {help: "'keep' to leave unrecognised contigs unchanged; 'drop' to remove their @SQ lines"}
        sample_id:     {help: "Used to name the output file: <sample_id>.ucsc.bam"}
    }
}
