version 1.0

## ─────────────────────────────────────────────────────────────────────────────
## rename_bam_chroms.wdl
##
## Workflow
## ────────
## Rename BAM/CRAM chromosome names from Ensembl style (1, 2, KI270419.1 …)
## to UCSC hg38 style (chr1, chr2, chrUn_KI270419v1 …) using the
## official UCSC chromAlias table and samtools reheader.
##
## Steps inside the task
## ─────────────────────
##   1. rename_bam_chroms.py  – rewrites @SQ header lines → tmp BAM
##   2. samtools sort          – coordinate-sort the tmp BAM
##   3. samtools index         – produce the .bai index (explicit in WDL)
##
## Inputs
## ──────
##   input_bam         File    – input BAM/CRAM with Ensembl-style contig names
##   input_bai         File?   – optional pre-existing index (localised alongside BAM)
##   rename_script     File    – rename_bam_chroms.py
##   chrom_alias       File?   – chromAlias.txt or chromAlias.txt.gz
##                               (downloaded from UCSC at runtime if not provided)
##   unmapped          String  – "keep" (default) or "drop"
##   sample_id         String  – used to name the output files
##
## Outputs
## ───────
##   renamed_bam       File    – output BAM with UCSC-style contig names
##   renamed_bai       File    – BAI index of the output BAM
## ─────────────────────────────────────────────────────────────────────────────

workflow RenameBamChroms {

    input {
        File    input_bam
        File?   input_bai
        File    rename_script
        File?   chrom_alias
        String  unmapped    = "keep"
        String  sample_id

        # Runtime overrides
        String  docker      = "us.gcr.io/broad-gatk/gatk:4.5.0.0"
        Int     cpu         = 4
        Int     mem_gb      = 16
        Int     disk_gb     = 200
        Int     preemptible = 2
    }

    call RenameContigs {
        input:
            input_bam     = input_bam,
            input_bai     = input_bai,
            rename_script = rename_script,
            chrom_alias   = chrom_alias,
            unmapped      = unmapped,
            sample_id     = sample_id,
            docker        = docker,
            cpu           = cpu,
            mem_gb        = mem_gb,
            disk_gb       = disk_gb,
            preemptible   = preemptible
    }

    output {
        File renamed_bam = RenameContigs.renamed_bam
        File renamed_bai = RenameContigs.renamed_bai
    }

    meta {
        author:      "Generated by Claude"
        description: "Rename BAM/CRAM contigs from Ensembl to UCSC hg38 naming using samtools reheader."
    }
}


# ─────────────────────────────────────────────────────────────────────────────
# Task: RenameContigs
# ─────────────────────────────────────────────────────────────────────────────
task RenameContigs {

    input {
        File    input_bam
        File?   input_bai
        File    rename_script
        File?   chrom_alias
        String  unmapped    = "keep"
        String  sample_id

        String  docker      = "us.gcr.io/broad-gatk/gatk:4.5.0.0"
        Int     cpu         = 4
        Int     mem_gb      = 16
        Int     disk_gb     = 200
        Int     preemptible = 2
    }

    String output_bam = "~{sample_id}.ucsc.bam"
    String output_bai = "~{sample_id}.ucsc.bam.bai"

    # Build the --alias argument only when the file is supplied
    String alias_arg = if defined(chrom_alias)
                       then "--alias ~{chrom_alias}"
                       else ""

    command <<<
        set -euo pipefail

        echo "[$(date '+%H:%M:%S')] Starting contig rename for ~{sample_id}"
        samtools --version | head -1
        python3 --version

        # ── Step 1: rewrite header, emit renamed BAM to temp file ──────────
        TMP_BAM="~{sample_id}.tmp.bam"

        python3 ~{rename_script} \
            --bam      ~{input_bam} \
            --out      "${TMP_BAM}" \
            ~{alias_arg} \
            --unmapped ~{unmapped}

        echo "[$(date '+%H:%M:%S')] Header rename complete. Sorting..."

        # ── Step 2: coordinate-sort (required before indexing) ─────────────
        samtools sort \
            -@ ~{cpu} \
            -o ~{output_bam} \
            "${TMP_BAM}"

        rm -f "${TMP_BAM}"
        echo "[$(date '+%H:%M:%S')] Sort complete. Indexing..."

        # ── Step 3: index — generates the .bai file ─────────────────────────
        samtools index -@ ~{cpu} ~{output_bam}

        echo "[$(date '+%H:%M:%S')] Done."

        # ── Sanity checks ───────────────────────────────────────────────────
        echo "--- First 5 @SQ lines in output header ---"
        samtools view -H ~{output_bam} | grep "^@SQ" | head -5

        N=$(samtools view -H ~{output_bam} | grep -c "^@SQ" || true)
        echo "Output BAM has ${N} @SQ contig header lines."

        echo "--- Output files ---"
        ls -lh ~{output_bam} ~{output_bai}
    >>>

    output {
        File renamed_bam = output_bam
        File renamed_bai = output_bai
    }

    runtime {
        docker:      docker
        cpu:         cpu
        memory:      "~{mem_gb} GB"
        disks:       "local-disk ~{disk_gb} HDD"
        preemptible: preemptible
        maxRetries:  1
    }

    meta {
        description: "Rename BAM/CRAM contig names from Ensembl to UCSC, sort, and index."
    }

    parameter_meta {
        input_bam:     {help: "Input BAM or CRAM with Ensembl-style contig names (e.g. 1, 2, KI270419.1)"}
        input_bai:     {help: "Optional BAI/CRAI index; supplying it ensures localisation alongside the BAM/CRAM"}
        rename_script: {help: "rename_bam_chroms.py script"}
        chrom_alias:   {help: "UCSC chromAlias.txt(.gz) — downloaded from UCSC at runtime if omitted"}
        unmapped:      {help: "'keep' to leave unrecognised contigs unchanged; 'drop' to remove their @SQ lines"}
        sample_id:     {help: "Used to name the output files: <sample_id>.ucsc.bam and .bai"}
    }
}
