version 1.0

## ─────────────────────────────────────────────────────────────────────────────
## classify_variants.wdl
##
## Workflow
## ────────
## For each contig-level VCF supplied in `contig_vcfs`, run classify_variants.py
## in parallel, then concatenate all per-contig BED outputs into a single
## genome-wide BED file (header written once, sorted by chrom then position).
##
## Inputs
## ──────
##   contig_vcfs      Array[File]  – one VCF(.gz) per contig/chromosome
##   contig_names     Array[String]– matching contig labels (e.g. "chr1", "chr2")
##                                   used only for naming intermediate files
##   gtf              File         – GTF or GTF.gz annotation (shared across tasks)
##   classify_script  File         – classify_variants.py
##   upstream_bp      Int          – bp window called "intergenic_upstream"  (default 2000)
##   downstream_bp    Int          – bp window called "intergenic_downstream" (default 2000)
##
## Outputs
## ───────
##   genome_bed       File  – merged, header-prefixed BED-like TSV
##   contig_beds      Array[File] – individual per-contig BED files
##
## Runtime
## ───────
## Designed for Google Cloud / Terra (Cromwell).  Adjust docker / memory /
## disk_gb / cpu as needed for your execution environment.
## ─────────────────────────────────────────────────────────────────────────────

workflow ClassifyVariantsWorkflow {

    input {
        Array[File]   contig_vcfs
        Array[String] contig_names
        File          gtf
        File          classify_script
        Int           upstream_bp   = 2000
        Int           downstream_bp = 2000

        # Runtime overrides (optional)
        String docker         = "python:3.11-slim"
        Int    classify_cpu   = 2
        Int    classify_mem   = 8       # GB
        Int    classify_disk  = 50      # GB
        Int    merge_cpu      = 2
        Int    merge_mem      = 4       # GB
        Int    merge_disk     = 100     # GB
    }

    # ── Validate that both arrays have the same length ────────────────────────
    # (WDL 1.0 will fail at scatter if lengths differ, but an explicit check
    #  gives a clearer error message)
    Int n_contigs = length(contig_vcfs)
    Int n_names   = length(contig_names)

    # Scatter: classify each contig in parallel
    scatter (i in range(n_contigs)) {
        call ClassifyContig {
            input:
                vcf              = contig_vcfs[i],
                contig_name      = contig_names[i],
                gtf              = gtf,
                classify_script  = classify_script,
                upstream_bp      = upstream_bp,
                downstream_bp    = downstream_bp,
                docker           = docker,
                cpu              = classify_cpu,
                mem_gb           = classify_mem,
                disk_gb          = classify_disk
        }
    }

    # Gather: merge per-contig BEDs into one genome-wide file
    call MergeBeds {
        input:
            contig_beds  = ClassifyContig.contig_bed,
            contig_names = contig_names,
            docker       = docker,
            cpu          = merge_cpu,
            mem_gb       = merge_mem,
            disk_gb      = merge_disk
    }

    output {
        File        genome_bed  = MergeBeds.genome_bed
        Array[File] contig_beds = ClassifyContig.contig_bed
    }

    meta {
        author:      "Generated by Claude"
        description: "Per-contig variant classification with classify_variants.py, merged genome-wide."
    }
}


# ─────────────────────────────────────────────────────────────────────────────
# Task: ClassifyContig
# Run classify_variants.py on a single contig VCF.
# ─────────────────────────────────────────────────────────────────────────────
task ClassifyContig {

    input {
        File   vcf
        String contig_name
        File   gtf
        File   classify_script
        Int    upstream_bp   = 2000
        Int    downstream_bp = 2000

        String docker  = "python:3.11-slim"
        Int    cpu     = 2
        Int    mem_gb  = 8
        Int    disk_gb = 50
    }

    # Output filename derived from contig name (safe for file systems)
    String safe_name  = sub(contig_name, "[^A-Za-z0-9_.-]", "_")
    String output_bed = "~{safe_name}.classified.bed"

    command <<<
        set -euo pipefail

        # ── install no extra packages; classify_variants.py uses stdlib only ──
        # If the GTF is gzip-compressed Python handles it natively.

        echo "[$(date '+%H:%M:%S')] Classifying contig: ~{contig_name}"

        python3 ~{classify_script} \
            --vcf          ~{vcf} \
            --gtf          ~{gtf} \
            --out          ~{output_bed} \
            --upstream-bp  ~{upstream_bp} \
            --downstream-bp ~{downstream_bp}

        echo "[$(date '+%H:%M:%S')] Done: $(wc -l < ~{output_bed}) lines written to ~{output_bed}"
    >>>

    output {
        File contig_bed = output_bed
    }

    runtime {
        docker:    docker
        cpu:       cpu
        memory:    "~{mem_gb} GB"
        disks:     "local-disk ~{disk_gb} HDD"
        preemptible: 2
        maxRetries:  1
    }

    meta {
        description: "Classify variants in a single contig VCF against a GTF annotation."
    }

    parameter_meta {
        vcf:             {help: "Single-contig VCF or VCF.gz"}
        contig_name:     {help: "Human-readable contig label (used in output filename)"}
        gtf:             {help: "GTF or GTF.gz gene annotation"}
        classify_script: {help: "classify_variants.py script file"}
        upstream_bp:     {help: "Max bp upstream of a gene to call intergenic_upstream"}
        downstream_bp:   {help: "Max bp downstream of a gene to call intergenic_downstream"}
    }
}


# ─────────────────────────────────────────────────────────────────────────────
# Task: MergeBeds
# Concatenate per-contig BED files in contig order, writing the header once.
# Also writes a summary count per classification class.
# ─────────────────────────────────────────────────────────────────────────────
task MergeBeds {

    input {
        Array[File]   contig_beds
        Array[String] contig_names

        String docker  = "python:3.11-slim"
        Int    cpu     = 2
        Int    mem_gb  = 4
        Int    disk_gb = 100
    }

    command <<<
        set -euo pipefail

        # Write ordered list of bed files to a manifest so the Python script
        # can read them in contig order (WDL Array serialisation is order-preserving).
        python3 - <<'PYEOF'
import sys

bed_files   = "~{sep=',' contig_beds}".split(",")
names       = "~{sep=',' contig_names}".split(",")
output_path = "genome_wide.classified.bed"
summary_path = "classification_summary.tsv"

from collections import Counter
counts = Counter()
header_written = False

with open(output_path, "w") as out:
    for name, bed in zip(names, bed_files):
        bed = bed.strip()
        if not bed:
            continue
        with open(bed) as fh:
            for i, line in enumerate(fh):
                line = line.rstrip("\n")
                if line.startswith("#"):
                    if not header_written:
                        out.write(line + "\n")
                        header_written = True
                    # skip duplicate headers from other contigs
                    continue
                out.write(line + "\n")
                # tally classification (column index 7)
                parts = line.split("\t")
                if len(parts) > 7:
                    counts[parts[7]] += 1

print(f"Merged {len(bed_files)} contig BED files → {output_path}", file=sys.stderr)

# Write summary
class_order = [
    "coding", "5UTR", "3UTR", "intronic",
    "intergenic_upstream", "intergenic_downstream"
]
total = sum(counts.values())
with open(summary_path, "w") as s:
    s.write("class\tcount\tpct\n")
    for cls in class_order:
        n = counts.get(cls, 0)
        pct = f"{n/total*100:.2f}" if total > 0 else "0.00"
        s.write(f"{cls}\t{n}\t{pct}\n")
    # catch any unexpected classes
    for cls, n in sorted(counts.items()):
        if cls not in class_order:
            pct = f"{n/total*100:.2f}" if total > 0 else "0.00"
            s.write(f"{cls}\t{n}\t{pct}\n")
    s.write(f"TOTAL\t{total}\t100.00\n")

print(f"Summary written → {summary_path}", file=sys.stderr)
PYEOF

        echo "[$(date '+%H:%M:%S')] Merge complete."
        wc -l genome_wide.classified.bed
        echo "--- Classification summary ---"
        cat classification_summary.tsv
    >>>

    output {
        File genome_bed  = "genome_wide.classified.bed"
        File summary_tsv = "classification_summary.tsv"
    }

    runtime {
        docker:    docker
        cpu:       cpu
        memory:    "~{mem_gb} GB"
        disks:     "local-disk ~{disk_gb} HDD"
        preemptible: 1
        maxRetries:  1
    }

    meta {
        description: "Concatenate per-contig BED files in order; write header once; produce class counts."
    }

    parameter_meta {
        contig_beds:  {help: "Per-contig BED files in contig order"}
        contig_names: {help: "Contig labels matching contig_beds order"}
    }
}
